spring:
  cloud:
    gateway:
      routes:
        - id: test_route    # - : 表示数组
          uri: https://www.zhihu.com
          predicates: #所有的断言规则
            #- Query=rul  #如果我们有‘rul’这个参数，那么我们就去‘https://www.zhihu.com’这个地址
            - Query=url,zhihu  #如果我们带 了“zhihu”，我们就跳转“https://www.zhihu.com”

        - id: jd_route
          uri: https://www.jd.com
          predicates:
            - Query=url,jd

        - id: admin_route
          uri: lb://renren-fast # 路由给renren-fast
          predicates:  # 什么情况下路由给它
            - Path=/api/** # 默认前端项目都带上api前缀，就是我们前面题的localhost:88/api
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}  # 把/api/* 改变成 /renren-fast/*

## 前端项目，统一加上  /api 统一标识符
## http://localhost:88/api/captcha.jpg    实际获取到的验证码请求地址：http://localhost:8080/renren-fast/captcha.ipg

#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: test_route  # - : 表示数组
#          uri: https://www.baidu.com
#          predicates: #所有的断言规则
#            #- Query=rul  #如果我们有‘rul’这个参数，那么我们就去‘https://www.baidu.com’这个地址
#            - Query=url,baidu    # 如果我们带 了“baidu”，我们就跳转“https://www.baidu.com”
#        - id: qq_route
#          uri: https://www.qq.com
#          predicates:
#            - Query=url,qq