spring:
  cloud:
    gateway:
      routes:
        - id: test_route    # - : 表示数组
          uri: https://www.zhihu.com
          predicates: #所有的断言规则
            #- Query=rul  #如果我们有‘rul’这个参数，那么我们就去‘https://www.zhihu.com’这个地址
            - Query=url,zhihu  #如果我们带 了“zhihu”，我们就跳转“https://www.zhihu.com”

        - id: jd_route
          uri: https://www.jd.com
          predicates:
            - Query=url,jd

#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: test_route  # - : 表示数组
#          uri: https://www.baidu.com
#          predicates: #所有的断言规则
#            #- Query=rul  #如果我们有‘rul’这个参数，那么我们就去‘https://www.baidu.com’这个地址
#            - Query=url,baidu    # 如果我们带 了“baidu”，我们就跳转“https://www.baidu.com”
#        - id: qq_route
#          uri: https://www.qq.com
#          predicates:
#            - Query=url,qq