spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI5tQJe43xkmKionyVWfkH
      secret-key: NYJesMLZJcVdFvhVx5bjEPw20vBe2z
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: gulimall-dali
  application:
    name: gulimall-third-party
server:
  port: 30000